<?php
$z[0]=Array("global","",189,215);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",267,293);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",984,1019);
$z[2][4]=array();
$z[2][4]['filename']="head.htm";
$z[3]=Array("include","",1033,1071);
$z[3][4]=array();
$z[3][4]['filename']="sidebar.htm";
$z[4]=Array("include","",4589,4626);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>