<?php
$z[0]=Array("type","[field:typelink/]",259,311);
$z[0][4]=array();
$z[0][4]['typeid']="12";
$z[1]=Array("type","[field:typelink/]",1164,1216);
$z[1][4]=array();
$z[1][4]['typeid']="18";
$z[2]=Array("type","[field:typelink/]",2077,2129);
$z[2][4]=array();
$z[2][4]['typeid']="14";
$z[3]=Array("type","[field:typelink/]",3473,3525);
$z[3][4]=array();
$z[3][4]['typeid']="19";
$z[4]=Array("type","[field:typelink/]",4141,4193);
$z[4][4]=array();
$z[4][4]['typeid']="20";

?>