<?php
$z[0]=Array("global","",195,221);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",273,299);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",2049,2084);
$z[2][4]=array();
$z[2][4]['filename']="head.htm";
$z[3]=Array("include","",2089,2127);
$z[3][4]=array();
$z[3][4]['filename']="sidebar.htm";
$z[4]=Array("include","",8604,8641);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>