<?php
$z[0]=Array("global","",186,212);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",264,290);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",991,1026);
$z[2][4]=array();
$z[2][4]['filename']="head.htm";
$z[3]=Array("include","",1040,1078);
$z[3][4]=array();
$z[3][4]['filename']="sidebar.htm";
$z[4]=Array("include","",5619,5656);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>