<?php
$z[0]=Array("global","",204,230);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",282,308);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1128,1163);
$z[2][4]=array();
$z[2][4]['filename']="head.htm";
$z[3]=Array("include","",1167,1205);
$z[3][4]=array();
$z[3][4]['filename']="sidebar.htm";
$z[4]=Array("include","",3551,3588);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>