<?php
$z[0]=Array("global","",213,239);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",291,317);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1185,1220);
$z[2][4]=array();
$z[2][4]['filename']="head.htm";
$z[3]=Array("include","",1224,1262);
$z[3][4]=array();
$z[3][4]['filename']="sidebar.htm";
$z[4]=Array("include","",5849,5886);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>