<?php
$z[0]=Array("global","",218,244);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",296,322);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",973,1008);
$z[2][4]=array();
$z[2][4]['filename']="head.htm";
$z[3]=Array("include","",1013,1051);
$z[3][4]=array();
$z[3][4]['filename']="sidebar.htm";
$z[4]=Array("include","",6555,6592);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>