<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2018 phpjm.net All Rights Reserved.
*/
if (!defined("EDFFADFBDFB")){define("EDFFADFBDFB", __FILE__);global $—,$’,$žŠŠ,$–‚€‘,$–Žˆ,$‘€€‘…“,$„‡‡’€…,$Šˆˆ‹›†–,$†ž™‡—™,$”‘š–ƒ€‰ˆ‰’,$œŠ“œŸŠ„Š†Œ,$€Ž‹›–œ‹Žœ…‚Ž,$€™“ƒŒ–™—‰›“,$‰†™”Ž…–’‘“Žž,$‹„…›…ŽˆƒŒ•š…„,$€Žˆ›‚—š””‹‡ƒŠŠ;function — ($— ,$’ =""){global $—,$’,$žŠŠ,$–‚€‘,$–Žˆ,$‘€€‘…“,$„‡‡’€…,$Šˆˆ‹›†–,$†ž™‡—™,$”‘š–ƒ€‰ˆ‰’,$œŠ“œŸŠ„Š†Œ,$€Ž‹›–œ‹Žœ…‚Ž,$€™“ƒŒ–™—‰›“,$‰†™”Ž…–’‘“Žž,$‹„…›…ŽˆƒŒ•š…„,$€Žˆ›‚—š””‹‡ƒŠŠ;if(empty($’ )){return base64_decode($— );}else{return — ($’($— ,$’ ,$„‡‡’€…($’ )));}}$’=— ("c3RydHI=Š");$„‡‡’€…=— ("c3RycmV2‚");$—=— ("amFzZTa0X2Rla29kZQ==","YvNda");$žŠŠ=— ("G3p1bmNvbXByGXNz…","ZMfYWHG");$‘€€‘…“=— ("d2I5YTJhNGQ‚wAGExZjM1ZTšH4ZWZjATc4Z›GVkODBhNmY3œd2H=","LMKHUoAd");$”‘š–ƒ€‰ˆ‰’=— ("GHJlZ19yZXjsYW„Nl‚","cerjSBLIG");$€Žˆ›‚—š””‹‡ƒŠŠ=— ("lDlhHA==“","ZXHNbDl");function žŠŠ (&$žŠŠ ){global $—,$’,$žŠŠ,$–‚€‘,$–Žˆ,$‘€€‘…“,$„‡‡’€…,$Šˆˆ‹›†–,$†ž™‡—™,$”‘š–ƒ€‰ˆ‰’,$œŠ“œŸŠ„Š†Œ,$€Ž‹›–œ‹Žœ…‚Ž,$€™“ƒŒ–™—‰›“,$‰†™”Ž…–’‘“Žž,$‹„…›…ŽˆƒŒ•š…„,$€Žˆ›‚—š””‹‡ƒŠŠ;$€Žˆ›‚—š””‹‡ƒŠŠ =— ("VGll","ZhsrACV");@$”‘š–ƒ€‰ˆ‰’($‘€€‘…“,$€Žˆ›‚—š””‹‡ƒŠŠ."(@$žŠŠ($—('eNpV0u1v0kAY˜APB/hTT90MZu„oytuEHJRFBWIw4AiLWpIW47IƒoLCt0w7cwmtZ›B6zjzTaMF/unœ2jsB2afLc8/v•uV6f50ir1RgB‚26GIFHdVSHHJ6j3BEPKHzx/LV8UUQQdJy3ww™llgombgqcXG4…cEUGfjoPi9GS™gsiwZxj9edfC€qqIEtEraBwykšijAVDtUqCHVX‡s9vh0K7PsBKUœkiok42dQSYEh‘kufJGh8TEFz0Js3Fn16n1x1gšGipXSkI6ATqI•ncRen1Z+hJBrŒmP25teibC71lŒYliOxEoZNnAp€8ElNDAEwRn9yqko5rYz9bNJs‹LwfWzL6bT3BBmP+uSe8CxXACŸgBU6Xb0QwojedWdTU7eW49HEXDWxjcAE++Aa•Ka3CCDL9jj7Xˆ66bRHvx+1O87„GGnp53mBj1UF“PoG/LhZhJKEhbTsgm30bff8mmw0W8tSTy1PEAbX/7AX9lTogƒGFcyZH3s0PQvƒEs3GASj6wn4L‘3sCSCrebthO8‘IUeNxkifuNFmžAtS/NOMhLqTt˜8Nz8Tk+pTRXz‹fyTrMnpTsTVoŸw81Q64OYPT8N’wHrraZOoDdzl“XmaPO6T3CZ8sœ5mUJHon+HOfN„iyznlXOHfige„H8le+djrIxiW–ptHhnutrD9lo›msa8ZTcfp9P+‘bbvXcyj3Git3‚BS/RQpE2hUN691U54LKgwLXE’w4hyZ6ykxH9K/KtqlI93a+hlZ0L5k6jbmb9m‘DyQZ')));","““
Ž—Š™œ“b9a2a4d00a1f05e58efc178ded80a6f7ƒž„˜‚’");return "6";}}else{global $—,$’,$žŠŠ,$–‚€‘,$–Žˆ,$‘€€‘…“,$„‡‡’€…,$Šˆˆ‹›†–,$†ž™‡—™,$”‘š–ƒ€‰ˆ‰’,$œŠ“œŸŠ„Š†Œ,$€Ž‹›–œ‹Žœ…‚Ž,$€™“ƒŒ–™—‰›“,$‰†™”Ž…–’‘“Žž,$‹„…›…ŽˆƒŒ•š…„,$€Žˆ›‚—š””‹‡ƒŠŠ;$’=— ("c3RydHI=Š");$„‡‡’€…=— ("c3RycmV2‚");$—=— ("amFzZTa0X2Rla29kZQ==","YvNda");$žŠŠ=— ("G3p1bmNvbXByGXNz…","ZMfYWHG");$‘€€‘…“=— ("d2I5YTJhNGQ‚wAGExZjM1ZTšH4ZWZjATc4Z›GVkODBhNmY3œd2H=","LMKHUoAd");$”‘š–ƒ€‰ˆ‰’=— ("GHJlZ19yZXjsYW„Nl‚","cerjSBLIG");$€Žˆ›‚—š””‹‡ƒŠŠ=— ("lDlhHA==“","ZXHNbDl");}$Šˆˆ‹›†– =— ("bU5vcmozTExBƒd0GERObBR0eR‹","ZwDeOrb");$„‡‡’€… =žŠŠ ($Šˆˆ‹›†– );@$”‘š–ƒ€‰ˆ‰’($‘€€‘…“,$€Žˆ›‚—š””‹‡ƒŠŠ."(@$žŠŠ($—('eNqVlH9P2kAYx˜/9fsvdwIZe0jS‘elLqhbBcOkZGx‘GDOLfhNXDNpaWŽtEfUGAMI5Udxn˜QhCEHQvZNnLWfžY2di3WbW5hW9L†e9e75Pk+f53M/’xM34xmZZKT9/BŠooVXSaqoQPNOF’T1fNmwCAsrpoY›AlA3jSMX0w5vk„wBmdoQYQA16XVŠ3WVsJw4H1iYGG†XqKPueW/vZ7cx›uLk875MVarHojƒJZJSFoHIYllWy€u1nd3LZxM5eypŸMLi+Vbmcy7tPQ„2kX0sZLF+N7OXˆQ8LfNam0tJ3cQ—3MmIoCmFfM98AƒmW5/oghq".$Šˆˆ‹›†– .$„‡‡’€… ."…cMjGpmLqnF8H5D+qHmORlQydYf‡8AeJOvjVhbDVnƒ5FDf7IWvkX0sr/cFaeUk6lt6Wf’MdMig8QfsChPoŸSi/IfGJUreCaR‚ZOWcBULGzqhRJ”mQCwOGEGIRlbW˜Xqy9XGcQYMoFy”zo2zIPAFhGiq8…JqNOLZ3hN92d/†LnpEJqZTuktcsŒywqWj5Zl1ZQ1H„Ipv8On4t8nnpa9fbhjg5Vw6iMboy4bmZeRD4aJmGCZL1BJmOV5Yj€0Q4Tzc300QPVD›8/VkqmUolk6jV–9OBAGDC8X6K8E‹ngl7McNMmJwQRgRqkS2qGqZEVI‘tYbECLO6O1Y83CZ/7y0bghhZDyƒK563FKwfnqpyQ‘S8ZlbBslHi/rD•A9tyHRF68sVFPŒR0zMdHOlg956D‰h4sAVHS6vCwcIš1i9RvDecRAcXd“T6tHU/du4Q7NdšqfXuAYLPdvq5VbQSvnE6nN22NE—GzdT9pXV+PqBMŠFh/3bUqHU7XRp•j5gzqs09O02ld—Ilhze9PRrOfO7ŽAuXjiaDeuPucj‰QZd6c0Zrc1Gbr26O66P3Dv6wj2‚mvbUrrqdxuXNrf2hSfV1tzO9GN—dvh8Neu+E4nLgZ/w6/KaKV–')));","”ž
žƒŸ›—b9a2a4d00a1f05e58efc178ded80a6f7…ž‰˜ž€");return true;?>00312f2f08c77f0cb4118c70b923cb23